version: '3.7'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    networks: 
      - kafka-local
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  
  
  broker:
    image: confluentinc/cp-kafka:7.4.0
    container_name: broker
    networks: 
      - kafka-local
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # OAuth Configuration
      KAFKA_SASL_SERVER_CALLBACK_HANDLER_CLASS: org.apache.kafka.common.security.oauthbearer.OAuthBearerValidatorCallbackHandler
      KAFKA_SASL_JAAS_CONFIG: org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required;
      KAFKA_SASL_OAUTHBEARER_JWKS_ENDPOINT_URL: https://nniikkoollaaii.github.io/kafka-sasl-oauthbearer-workload-identity/openid/v1/jwks # To edit
      KAFKA_SASL_OAUTHBEARER_SCOPE_CLAIM: scp

      
  # test-producer:
  #   image: io.github.nniikkoollaaii.kafka-producer-app:1.0.0
  #   container_name: producer
  #   environment:
  #     CLIENT_ID: "c8843062-a9dc-49ed-8874-3b2d911ca41a"
  #     CLIENT_SECRET: ""
  #     BOOTSTRAP_SERVERS: "broker:9092"
  #   networks: 
  #     - kafka-local

networks: 
  kafka-local: