version: '3.7'

services:

  broker:
    image: confluentinc/confluent-local:latest
    hostname: broker
    container_name: broker
    ports:
      - 29092:29092
      - 9092:9092
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # OAuth Configuration
      KAFKA_SASL_SERVER_CALLBACK_HANDLER_CLASS: org.apache.kafka.common.security.oauthbearer.OAuthBearerValidatorCallbackHandler
      KAFKA_SASL_JAAS_CONFIG: org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required;
      KAFKA_SASL_OAUTHBEARER_JWKS_ENDPOINT_URL: https://nniikkoollaaii.github.io/kafka-sasl-oauthbearer-workload-identity/openid/v1/jwks # To edit
      KAFKA_SASL_OAUTHBEARER_SCOPE_CLAIM: scp

    networks: 
      - kafka-local
      
  # test-producer:
  #   image: io.github.nniikkoollaaii.kafka-producer-app:1.0.0
  #   container_name: producer
  #   environment:
  #     CLIENT_ID: "c8843062-a9dc-49ed-8874-3b2d911ca41a"
  #     CLIENT_SECRET: ""
  #     BOOTSTRAP_SERVERS: "broker:29092"
  #   networks: 
  #     - kafka-local

networks: 
  kafka-local: