apiVersion: v1
kind: Pod
metadata:
  name: test-consumer
  namespace: test
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: sa-test
  restartPolicy: Never
  containers:
    - image: io.github.nniikkoollaaii.kafka-consumer-app:1.0.0
      name: consumer
      env:
      - name: BOOTSTRAP_SERVERS
        value: "broker:9092"
      - name: KAFKA_SSL_TRUSTSTORE_LOCATION
        value: "/var/ssl/private/truststore/kafka.truststore.jks"
      - name: KAFKA_SSL_TRUSTSTORE_PASSWORD
        value: "123456"