apiVersion: v1
kind: Pod
metadata:
  name: test-producer
  namespace: test
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: sa-test
  restartPolicy: Never
  containers:
    - image: io.github.nniikkoollaaii.kafka-producer-app:1.0.0
      name: producer
      env:
      - name: BOOTSTRAP_SERVERS
        value: "broker:9092"
      - name: MESSAGE_CONTENT
        value: "{BUILD_NUMBER}"
      - name: KAFKA_SSL_TRUSTSTORE_LOCATION
        value: "/var/ssl/private/truststore/kafka.truststore.jks"
      - name: KAFKA_SSL_TRUSTSTORE_PASSWORD
        value: "123456"
      - name: SCHEMA_REGISTRY_URL
        value: "http://schema-registry:8081"