apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: ${APPLICATION_CLIENT_ID:-$USER_ASSIGNED_IDENTITY_CLIENT_ID}
  name: sa-test
  namespace: test
---
apiVersion: v1
kind: Pod
metadata:
  name: test-producer
  namespace: test
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: sa-test
  containers:
    - image: de.nniikkoollaaii.kafka-producer-app:1.0.0
      name: producer