apiVersion: v1
kind: Pod
metadata:
  name: test-producer
  namespace: test
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: sa-test
  restartPolicy: Never
  containers:
    - image: io.github.nniikkoollaaii.kafka-producer-app:1.0.0
      name: producer
      env:
      - name: BOOTSTRAP_SERVERS
        value: "broker:9092"
      - name: MESSAGE_CONTENT
        value: "{BUILD_NUMBER}"