# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


env:
  KIND_CLUSTER_NAME: "cluster"


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B install --file pom.xml --no-transfer-progress -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # comment out because of error "Error: Could not generate a snapshot of the dependencies; Maximum call stack size exceeded"
    #- name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      
            
    - name: Prepare KinD config
      run: |
        # Copy private key for E2E test to file
        echo "${{ secrets.E2E_SA_KEY_2 }}" > ./e2e/sa.key
        echo "Created file ./e2e/sa.key"
        

        echo "Set current dir $(pwd) in kind.config"
        sed -i "s|{E2E_DIR_PATH}|$(pwd)|g" ./e2e/kind.config

        echo "KinD Config:"
        cat ./e2e/kind.config
      shell: bash
        
    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.7.0
      with:
        cluster_name: ${{ env.KIND_CLUSTER_NAME }}
        config: e2e/kind.config
        #version: 1.24.0
        #install_only: true
        #wait: 180s

    - uses: azure/setup-kubectl@v3
      name: Install kubectl
    - uses: azure/setup-helm@v3
      name: Install helm

    - name: Run test script
      run: |
        chmod +x ./e2e/test.sh
        ./e2e/test.sh
      shell: bash
      env: 
        BUILD_NUMBER: ${{github.run_number}}